config/routes.rb
Rails.application.routes.draw do
  root 'notes#index'

  resources :notes do
  	resources :comments
  end
  	
  devise_for :users
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :note
	belongs_to :user
end
 

app/models/note.rb
class Note < ApplicationRecord
	belongs_to :user
	has_many :comments
end
 

app/models/user.rb
class User < ApplicationRecord
	has_many :notes
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end
 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :set_comment, only: [:show, :edit, :update, :destroy]
	before_action :set_note, only: [:index, :create, :show, :edit, :update, :destroy]
    
    def index
    end

	def create		
		@comment = @note.comments.build(comments_params)
		@comment.user = current_user
		@comment.save

		redirect_to notes_url
	end

	def edit
	end

	def show
  	end

	def update
    respond_to do |format|
      if @comment.update(comments_params)
        format.html { redirect_to root_url, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end


	def destroy
		@note = Note.find(params[:note_id])
		@comment = @note.comments.find(params[:id]).destroy

		redirect_to notes_url
	end

	private


	def set_comment
		@comment = Comment.find(params[:id])
	end

	def set_note
		@note = Note.find(params[:note_id])
	end

	def comments_params
		params.require(:comment).permit(:content)
		
	end
end	

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]
  before_action :set_user, only: [:index, :create]
  # GET /notes
  # GET /notes.json
  def index
    @notes = @user.notes.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note = @user.notes.build(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_user
      @user = current_user
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/comments/_comment.html.erb
<p>
   <%= comment.content %>
	<br>
   <%= link_to 'Edit',  edit_note_comment_path(comment.note, comment) , class: "btn btn-outline-primary" %>
   <%= link_to 'Delete', note_comment_path(comment.note, comment), class: "btn btn-outline-danger" ,method: :delete %>
</p> 

app/views/comments/_form.html.erb
  <div class="form-group">
  	<%= form_with(model: comment, url: [note, comment], local: true) do |form| %> 

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content , class: "form-control"%>
  </div>
  
  <div class="actions">
    <%= form.submit %>
   <% end %>
  </div>
</div>
 

app/views/comments/edit.html.erb
<div> 
<div class="text-center"> <h1><i>Editing Comment</i></h1></div>
 
<b><big><%= render 'form', comment: @comment , note: @note %></big></b>

<%= link_to 'Back', root_url %>
</div>
 

app/views/comments/index.html.erb
<%= content_for :comment do %>
 <h4> Comments </h4> 
	<%= render @note.comments %>
 <hr>
 <p> Add Your Points : As comments here -- </p>
  <%= form_for([@note, @note.comments.build]) do |f| %>
	<%= f.text_area :content %>
	<%= submit_tag "Add" %>
  <% end %>
<% end %>

app/views/layouts/_nav.html.erb
<header class="navbar navbar-expand-lg navbar navbar-light bg-dark">
  <div class="container">
    <%= link_to "Simple Notes App", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><%= link_to "Home", root_path %></li> -->
        
        <% if signed_in? %>
          <!-- <li><%= link_to "Users", notes_path %></li> -->
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Profile <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Details", edit_user_password_path %></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              <li class="divider"></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in"%></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<div class="wrapper">
  <nav id="sidebar" class="side-nav side-nav-dark">
    <ul class="list-unstyled components">
      <% content_for :nav_links do %>
        <li class="active">
          <% @notes.each do |note| %>
            <%= link_to note.title , note_comments_path(note) %>
          <% end %>
        </li>
      <% end %> 
      <%= yield :nav_links %>
    </ul>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title>SimpleNotesApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= render 'layouts/nav' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-color: #7EE5B5">
    
    <div class="container-fluid">
    <%= yield %>
    </div>

    <div class="col-md-10 text-center">
        <%= yield (:comment) %>
                   <br>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

app/views/notes/_comment.html.erb
 <h4> Comments </h4> 
	<%= render @note.comments %>
<hr>
<p> Add Your Points : As comments here -- </p>
<% form_for([@note, @note.comments.build]) do |f| %>
	<%= f.text_area :content %>
	<%= submit_tag "Add" %>
<% end %>

app/views/notes/_form.html.erb
<div class="form-group">
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %> 

  <div class="field">
    <b><%= form.label :title %></b>
    <%= form.text_field :title , class: "form-control" %>
  </div>

  <div class="field">
    <b><%= form.label :description %></b>
    <%= form.text_area :description , class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/notes/edit.html.erb
<div class="text-center">
	<h1>
		<i>Editing Note</i>
	</h1>
</div>
<%= render 'form', note: @note %>

<%= link_to 'Show', @note , class: "btn btn-primary btn-sm" %> |
<%= link_to 'Back', notes_path , class: "btn btn-secondary btn-sm" %>

app/views/notes/index.html.erb
<div style="margin-left: 50px">
  <%= link_to 'Create Note', new_note_path , class: "btn btn-info" %>
  <%= link_to "Log out", destroy_user_session_path, class: "btn btn-dark", method: :delete %>
</div>
<div class="sidebar">
  <%= render 'layouts/sidebar' %>
</div>
<div>
  <% @notes.each do |note| %>
    <div class="main">
      <%= yield %>
    </div>
  <% end %>
</div>

app/views/notes/new.html.erb
<div class="form-group">
	<h1>New Note</h1>
	<%= render 'form', note: @note %>
	<%= link_to 'Back', notes_path %>
</div>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @note.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @note.description %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>